package com.qf.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.qf.express.common.DataGridResult;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2018-11-06T15:38:12.284+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://api.manage.express.qf.com/", name = "DecidedzoneService")
public interface DecidedzoneService {

    @WebMethod
    @RequestWrapper(localName = "findDecidedzone", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindDecidedzone")
    @ResponseWrapper(localName = "findDecidedzoneResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindDecidedzoneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult<BcDecidedzone> findDecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );
}
