package com.qf.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2018-11-07T14:50:38.486+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://api.manage.express.qf.com/", name = "QpService")
public interface QpService {

    @WebMethod
    @RequestWrapper(localName = "findAllStaff", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllStaff")
    @ResponseWrapper(localName = "findAllStaffResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllStaffResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qf.express.manage.client.BcStaff> findAllStaff();

    @WebMethod
    @RequestWrapper(localName = "updateForAss", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.UpdateForAss")
    @ResponseWrapper(localName = "updateForAssResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.UpdateForAssResponse")
    public void updateForAss(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.QpNoticebill arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllNoAss", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllNoAss")
    @ResponseWrapper(localName = "findAllNoAssResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllNoAssResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qf.express.manage.client.QpNoticebill> findAllNoAss();

    @WebMethod
    @RequestWrapper(localName = "addQp", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddQp")
    @ResponseWrapper(localName = "addQpResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddQpResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.qf.express.manage.client.BcStaff addQp(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.QpNoticebill arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws Exception;
}
