package com.qf.express.manage.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.qf.express.common.AppResult;
import com.qf.express.common.DataGridResult;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2018-11-06T15:45:41.339+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://api.manage.express.qf.com/", name = "RegionService")
public interface RegionService {

    @WebMethod
    @RequestWrapper(localName = "addSubarea", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddSubarea")
    @ResponseWrapper(localName = "addSubareaResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddSubareaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult addSubarea(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.BcSubarea arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addregion", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.Addregion")
    @ResponseWrapper(localName = "addregionResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddregionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult addregion(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.BcRegion arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delSubarea", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.DelSubarea")
    @ResponseWrapper(localName = "delSubareaResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.DelSubareaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult delSubarea(
        @WebParam(name = "arg0", targetNamespace = "")
        String[] id
    );

    @WebMethod
    @RequestWrapper(localName = "findAllRegion", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllRegion")
    @ResponseWrapper(localName = "findAllRegionResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllRegionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qf.express.manage.client.BcRegion> findAllRegion();

    @WebMethod
    @RequestWrapper(localName = "findRegion", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRegion")
    @ResponseWrapper(localName = "findRegionResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRegionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult<BcRegion> findRegion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findSubarea", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindSubarea")
    @ResponseWrapper(localName = "findSubareaResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindSubareaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult<BcSubarea> findSubarea(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "addRegions", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddRegions")
    @ResponseWrapper(localName = "addRegionsResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddRegionsResponse")
    public void addRegions(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.qf.express.manage.client.BcRegion> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delregion", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.Delregion")
    @ResponseWrapper(localName = "delregionResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.DelregionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult delregion(
        @WebParam(name = "arg0", targetNamespace = "")
        String[] id
    );

    @WebMethod
    @RequestWrapper(localName = "findRegionsByKeys", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRegionsByKeys")
    @ResponseWrapper(localName = "findRegionsByKeysResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRegionsByKeysResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qf.express.manage.client.BcRegion> findRegionsByKeys(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
