package com.qf.express.manage.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.qf.express.common.AppResult;
import com.qf.express.common.DataGridResult;
import com.qf.express.common.UserCombobox;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2018-11-06T15:53:18.822+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://api.manage.express.qf.com/", name = "UserService")
public interface UserService {

    @WebMethod
    @RequestWrapper(localName = "addRole", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddRole")
    @ResponseWrapper(localName = "addRoleResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult addRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.Role arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delchildrright", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.Delchildrright")
    @ResponseWrapper(localName = "delchildrrightResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.DelchildrrightResponse")
    public void delchildrright(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "findUsersForLogin", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindUsersForLogin")
    @ResponseWrapper(localName = "findUsersForLoginResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindUsersForLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.qf.express.manage.client.Users findUsersForLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "updUser", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.UpdUser")
    @ResponseWrapper(localName = "updUserResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.UpdUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult updUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.Users arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delrolesbychecked", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.Delrolesbychecked")
    @ResponseWrapper(localName = "delrolesbycheckedResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.DelrolesbycheckedResponse")
    public void delrolesbychecked(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllRole", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllRole")
    @ResponseWrapper(localName = "findAllRoleResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAllRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public List<UserCombobox> findAllRole();

    @WebMethod
    @RequestWrapper(localName = "findRRightsForCurd", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRRightsForCurd")
    @ResponseWrapper(localName = "findRRightsForCurdResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRRightsForCurdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qf.express.manage.client.Rright> findRRightsForCurd(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "addOrUpdateRight", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddOrUpdateRight")
    @ResponseWrapper(localName = "addOrUpdateRightResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddOrUpdateRightResponse")
    public void addOrUpdateRight(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.Rright arg0
    );

    @WebMethod
    @RequestWrapper(localName = "delusersbychecked", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.Delusersbychecked")
    @ResponseWrapper(localName = "delusersbycheckedResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.DelusersbycheckedResponse")
    public void delusersbychecked(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findARolesByInput", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindARolesByInput")
    @ResponseWrapper(localName = "findARolesByInputResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindARolesByInputResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult<Role> findARolesByInput(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod
    @RequestWrapper(localName = "findRRightsForMenu", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRRightsForMenu")
    @ResponseWrapper(localName = "findRRightsForMenuResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRRightsForMenuResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qf.express.manage.client.Rright> findRRightsForMenu(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "checkrightname", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.Checkrightname")
    @ResponseWrapper(localName = "checkrightnameResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.CheckrightnameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Boolean checkrightname(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAUsersByInput", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAUsersByInput")
    @ResponseWrapper(localName = "findAUsersByInputResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindAUsersByInputResponse")
    @WebResult(name = "return", targetNamespace = "")
    public DataGridResult<Users> findAUsersByInput(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod
    @RequestWrapper(localName = "updRole", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.UpdRole")
    @ResponseWrapper(localName = "updRoleResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.UpdRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult updRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.Role arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addUser", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.AddUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public AppResult addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.qf.express.manage.client.Users arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findRrighttext", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRrighttext")
    @ResponseWrapper(localName = "findRrighttextResponse", targetNamespace = "http://api.manage.express.qf.com/", className = "com.qf.express.manage.client.FindRrighttextResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.qf.express.manage.client.Users> findRrighttext(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
